on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make
        run: make all
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v2023.2.20230920.1"
          artifacts: "AL2023.zip"
